title: Quynh Le {text-align: center;} # your name (or website title) here
logo: "/images/ql-transparent.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  AI Research Resident 
  <br><br>
  @ VinAI Research - Vietnam 
  <br><br>
  Research Interest: 3D object detection 
  <br><br>
  <a href="https://www.linkedin.com/in/quynhtle/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
