title: Quynh Le # your name (or website title) here
logo: "/images/ql-transparent.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  AI Research Resident 
  <br><br>
  @ VinAI Research - Vietnam 
  <br><br>
  Research Interest: 3D object detection 
  <br><br>
  <a href="https://www.linkedin.com/in/quynhtle/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

---

<style type="text/css">

h1.title {
#   font-size: 38px;
#   color: DarkRed;
  text-align: center;
}
# h4.author { /* Header 4 - and the author and data headers use this too  */
#     font-size: 18px;
#   font-family: "Times New Roman", Times, serif;
#   color: DarkRed;
#   text-align: center;
# }
# h4.date { /* Header 4 - and the author and data headers use this too  */
#   font-size: 18px;
#   font-family: "Times New Roman", Times, serif;
#   color: DarkBlue;
#   text-align: center;
# }
</style>
